use crate::table::{escape_tsv, valid_schema_id};
use crate::{OutputError, ResultContext, ResultEnvelope};
use serde::{Deserialize, Serialize};
use std::collections::BTreeSet;
use std::io::{BufWriter, Write};
use std::path::Path;

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct MexFeature {
    pub id: String,
    pub name: String,
    #[serde(default = "default_feature_type")]
    pub feature_type: String,
}

fn default_feature_type() -> String {
    "Gene Expression".into()
}

#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MatrixValue {
    Integer(i64),
    Real(f64),
}

#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatrixEntry {
    /// Zero-based feature row.
    pub feature: usize,
    /// Zero-based barcode column.
    pub barcode: usize,
    pub value: MatrixValue,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SparseMatrix {
    pub schema_id: String,
    pub features: Vec<MexFeature>,
    pub barcodes: Vec<String>,
    pub entries: Vec<MatrixEntry>,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct MexManifest {
    pub format: String,
    pub matrix: String,
    pub features: String,
    pub barcodes: String,
    pub feature_count: usize,
    pub barcode_count: usize,
    pub nonzero_count: usize,
    pub index_base: usize,
    pub value_type: String,
}

/// Create a standard feature-by-barcode Matrix Market exchange directory. The destination must not
/// already exist. `metadata.json` is written last and therefore acts as the completion marker.
pub fn write_mex_new(
    directory: &Path,
    matrix: &SparseMatrix,
    context: ResultContext,
) -> Result<MexManifest, OutputError> {
    validate(matrix)?;
    context.validate()?;
    std::fs::create_dir(directory).map_err(|error| {
        if error.kind() == std::io::ErrorKind::AlreadyExists {
            OutputError::InvalidMatrix(format!(
                "refusing to overwrite existing MEX output {}",
                directory.display()
            ))
        } else {
            OutputError::Io(error)
        }
    })?;

    let real = matrix
        .entries
        .iter()
        .any(|entry| matches!(entry.value, MatrixValue::Real(_)));
    let mut entries = matrix.entries.clone();
    entries.sort_by_key(|entry| (entry.feature, entry.barcode));

    let matrix_path = directory.join("matrix.mtx");
    let mut matrix_writer = BufWriter::new(create_new(&matrix_path)?);
    writeln!(
        matrix_writer,
        "%%MatrixMarket matrix coordinate {} general",
        if real { "real" } else { "integer" }
    )?;
    writeln!(
        matrix_writer,
        "% generated by Gravlax; rows=features columns=barcodes"
    )?;
    writeln!(
        matrix_writer,
        "{} {} {}",
        matrix.features.len(),
        matrix.barcodes.len(),
        entries.len()
    )?;
    for entry in &entries {
        write!(
            matrix_writer,
            "{} {} ",
            entry.feature + 1,
            entry.barcode + 1
        )?;
        match entry.value {
            MatrixValue::Integer(value) if !real => writeln!(matrix_writer, "{value}")?,
            MatrixValue::Integer(value) => writeln!(matrix_writer, "{value}.0")?,
            MatrixValue::Real(value) => writeln!(matrix_writer, "{value}")?,
        }
    }
    matrix_writer.flush()?;

    let features_path = directory.join("features.tsv");
    let mut features_writer = BufWriter::new(create_new(&features_path)?);
    for feature in &matrix.features {
        writeln!(
            features_writer,
            "{}\t{}\t{}",
            escape_tsv(&feature.id),
            escape_tsv(&feature.name),
            escape_tsv(&feature.feature_type)
        )?;
    }
    features_writer.flush()?;

    let barcodes_path = directory.join("barcodes.tsv");
    let mut barcodes_writer = BufWriter::new(create_new(&barcodes_path)?);
    for barcode in &matrix.barcodes {
        writeln!(barcodes_writer, "{}", escape_tsv(barcode))?;
    }
    barcodes_writer.flush()?;

    let manifest = MexManifest {
        format: "matrix_market_coordinate".into(),
        matrix: "matrix.mtx".into(),
        features: "features.tsv".into(),
        barcodes: "barcodes.tsv".into(),
        feature_count: matrix.features.len(),
        barcode_count: matrix.barcodes.len(),
        nonzero_count: entries.len(),
        index_base: 1,
        value_type: if real { "real" } else { "integer" }.into(),
    };
    let envelope = ResultEnvelope::new(matrix.schema_id.clone(), context, manifest.clone())?;
    let metadata_path = directory.join("metadata.json");
    let mut metadata_writer = BufWriter::new(create_new(&metadata_path)?);
    serde_json::to_writer_pretty(&mut metadata_writer, &envelope)?;
    writeln!(metadata_writer)?;
    metadata_writer.flush()?;
    Ok(manifest)
}

fn create_new(path: &Path) -> Result<std::fs::File, OutputError> {
    Ok(std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path)?)
}

fn validate(matrix: &SparseMatrix) -> Result<(), OutputError> {
    if !valid_schema_id(&matrix.schema_id) {
        return Err(OutputError::InvalidMatrix(
            "schema id must be non-empty ASCII letters, digits, '.', '_' or '-'".into(),
        ));
    }
    let mut feature_ids = BTreeSet::new();
    for feature in &matrix.features {
        if feature.id.is_empty() {
            return Err(OutputError::InvalidMatrix(
                "feature ids must not be empty".into(),
            ));
        }
        if !feature_ids.insert(&feature.id) {
            return Err(OutputError::InvalidMatrix(format!(
                "duplicate feature id {:?}",
                feature.id
            )));
        }
    }
    let mut barcodes = BTreeSet::new();
    for barcode in &matrix.barcodes {
        if barcode.is_empty() {
            return Err(OutputError::InvalidMatrix(
                "barcodes must not be empty".into(),
            ));
        }
        if !barcodes.insert(barcode) {
            return Err(OutputError::InvalidMatrix(format!(
                "duplicate barcode {barcode:?}"
            )));
        }
    }
    let mut coordinates = BTreeSet::new();
    for (index, entry) in matrix.entries.iter().enumerate() {
        if entry.feature >= matrix.features.len() || entry.barcode >= matrix.barcodes.len() {
            return Err(OutputError::InvalidMatrix(format!(
                "entry {index} is outside the {} x {} matrix",
                matrix.features.len(),
                matrix.barcodes.len()
            )));
        }
        if !coordinates.insert((entry.feature, entry.barcode)) {
            return Err(OutputError::InvalidMatrix(format!(
                "duplicate entry at feature {}, barcode {}",
                entry.feature, entry.barcode
            )));
        }
        match entry.value {
            MatrixValue::Integer(0) => {
                return Err(OutputError::InvalidMatrix(format!(
                    "entry {index} is explicitly zero"
                )))
            }
            MatrixValue::Real(value) if value == 0.0 || !value.is_finite() => {
                return Err(OutputError::InvalidMatrix(format!(
                    "entry {index} is zero or non-finite"
                )))
            }
            _ => {}
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    struct TempDir(std::path::PathBuf);

    impl TempDir {
        fn path(&self) -> &Path {
            &self.0
        }
    }

    impl Drop for TempDir {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.0);
        }
    }

    fn output_path() -> TempDir {
        TempDir(std::env::temp_dir().join(format!(
            "gravlax-mex-{}-{:x}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        )))
    }

    fn matrix() -> SparseMatrix {
        SparseMatrix {
            schema_id: "gravlax.replay.gene-matrix.v1".into(),
            features: vec![MexFeature {
                id: "ENSG1".into(),
                name: "ALPHA".into(),
                feature_type: "Gene Expression".into(),
            }],
            barcodes: vec!["CELL-1".into(), "CELL-2".into()],
            entries: vec![
                MatrixEntry {
                    feature: 0,
                    barcode: 1,
                    value: MatrixValue::Integer(3),
                },
                MatrixEntry {
                    feature: 0,
                    barcode: 0,
                    value: MatrixValue::Integer(2),
                },
            ],
        }
    }

    #[test]
    fn writes_guarded_standard_mex_with_manifest_last() {
        let output = output_path();
        let manifest = write_mex_new(output.path(), &matrix(), ResultContext::default()).unwrap();
        assert_eq!(manifest.nonzero_count, 2);
        let mtx = std::fs::read_to_string(output.path().join("matrix.mtx")).unwrap();
        assert!(mtx.starts_with("%%MatrixMarket matrix coordinate integer general\n"));
        assert!(mtx.contains("1 2 2\n1 1 2\n1 2 3\n"));
        let metadata: serde_json::Value =
            serde_json::from_slice(&std::fs::read(output.path().join("metadata.json")).unwrap())
                .unwrap();
        assert_eq!(metadata["result_schema"], "gravlax.replay.gene-matrix.v1");
        assert_eq!(metadata["data"]["index_base"], 1);
        assert!(write_mex_new(output.path(), &matrix(), ResultContext::default()).is_err());
    }

    #[test]
    fn rejects_duplicate_out_of_bounds_zero_and_nonfinite_entries() {
        let mut invalid = matrix();
        invalid.entries.push(invalid.entries[0]);
        assert!(validate(&invalid).is_err());
        invalid.entries.pop();
        invalid.entries[0].feature = 99;
        assert!(validate(&invalid).is_err());
        invalid.entries[0] = MatrixEntry {
            feature: 0,
            barcode: 1,
            value: MatrixValue::Real(f64::NAN),
        };
        assert!(validate(&invalid).is_err());
    }

    #[test]
    fn rejects_duplicate_labels_and_invalid_schema_ids() {
        let mut invalid = matrix();
        invalid.features.push(invalid.features[0].clone());
        assert!(validate(&invalid)
            .unwrap_err()
            .to_string()
            .contains("duplicate feature id"));

        let mut invalid = matrix();
        invalid.barcodes.push(invalid.barcodes[0].clone());
        assert!(validate(&invalid)
            .unwrap_err()
            .to_string()
            .contains("duplicate barcode"));

        let mut invalid = matrix();
        invalid.schema_id = "invalid schema".into();
        assert!(validate(&invalid)
            .unwrap_err()
            .to_string()
            .contains("schema id"));
    }
}
