from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tarfile
import tempfile
import tomllib
import unittest
import zipfile


ROOT = Path(__file__).resolve().parents[2]
PYTHON = sys.executable


class DistributionTests(unittest.TestCase):
    def test_workspace_python_and_local_conda_versions_match(self):
        cargo = tomllib.loads((ROOT / "Cargo.toml").read_text(encoding="utf-8"))
        pyproject = tomllib.loads((ROOT / "python/pyproject.toml").read_text(encoding="utf-8"))
        python_init = (ROOT / "python/src/gravlax/__init__.py").read_text(encoding="utf-8")
        docs = json.loads((ROOT / "docs/package.json").read_text(encoding="utf-8"))
        docs_lock = json.loads((ROOT / "docs/package-lock.json").read_text(encoding="utf-8"))
        version = cargo["workspace"]["package"]["version"]
        self.assertEqual(version, pyproject["project"]["version"])
        self.assertIn(f'__version__ = "{version}"', python_init)
        self.assertEqual(version, docs["version"])
        self.assertEqual(version, docs_lock["version"])
        self.assertEqual(version, docs_lock["packages"][""]["version"])
        local_recipe = (ROOT / "packaging/conda/local/meta.yaml").read_text(encoding="utf-8")
        self.assertIn(f'environ.get("GRAVLAX_VERSION", "{version}")', local_recipe)

        accepted = subprocess.run(
            [
                PYTHON,
                str(ROOT / "packaging/release_version.py"),
                "--tag",
                f"v{version}",
                "--repository",
                str(ROOT),
            ],
            check=True,
            capture_output=True,
            text=True,
        )
        self.assertEqual(accepted.stdout.strip(), version)
        rejected = subprocess.run(
            [
                PYTHON,
                str(ROOT / "packaging/release_version.py"),
                "--tag",
                f"release-{version}",
                "--repository",
                str(ROOT),
            ],
            capture_output=True,
            text=True,
        )
        self.assertNotEqual(rejected.returncode, 0)

    def test_cargo_dist_workflow_is_generated_and_composes_release_channels(self):
        cargo = tomllib.loads((ROOT / "Cargo.toml").read_text(encoding="utf-8"))
        dist = cargo["workspace"]["metadata"]["dist"]
        self.assertEqual(dist["cargo-dist-version"], "0.32.0")
        self.assertEqual(dist["ci"], "github")
        self.assertEqual(dist["hosting"], "github")
        self.assertTrue(dist["github-attestations"])
        self.assertFalse(dist["source-tarball"])
        self.assertEqual(
            dist["min-glibc-version"], {"x86_64-unknown-linux-gnu": "2.35"}
        )
        self.assertEqual(
            dist["publish-jobs"],
            ["./publish-crates"],
        )
        self.assertEqual(dist["local-artifacts-jobs"], ["./release-checks"])
        self.assertNotIn("plan-jobs", dist)
        self.assertEqual(
            dist["github-build-setup"],
            "cargo-dist/release-build-setup.yml",
        )
        self.assertEqual(dist["github-release"], "announce")
        self.assertEqual(
            tomllib.loads((ROOT / "rust-toolchain.toml").read_text(encoding="utf-8"))[
                "toolchain"
            ],
            {"channel": "1.98.0", "profile": "minimal"},
        )

        workflow = (ROOT / ".github/workflows/release.yml").read_text(encoding="utf-8")
        self.assertIn("This file was autogenerated by dist", workflow)
        self.assertIn("cargo-dist/releases/download/v0.32.0", workflow)
        self.assertEqual(
            dist["targets"],
            [
                "aarch64-apple-darwin",
                "x86_64-apple-darwin",
                "x86_64-unknown-linux-gnu",
                "x86_64-unknown-linux-musl",
                "x86_64-pc-windows-msvc",
            ],
        )
        for reusable in (
            "release-checks.yml",
            "build-release-extras.yml",
            "publish-crates.yml",
        ):
            self.assertIn(reusable, workflow)
        self.assertEqual(
            workflow.count("uses: ./.github/workflows/release-checks.yml"),
            1,
        )
        custom_release_checks = workflow[
            workflow.index("  custom-release-checks:") : workflow.index(
                "  build-global-artifacts:"
            )
        ]
        self.assertIn("- plan", custom_release_checks)
        # Cargo-dist permits skipped artifact jobs in its generic host condition,
        # but this predicate guarantees that the checks run for every publication.
        # An actual check failure therefore still blocks hosting.
        self.assertIn(
            "needs.plan.outputs.publishing == 'true'",
            custom_release_checks,
        )
        for job_start, job_end in (
            ("  build-global-artifacts:", "  custom-build-release-extras:"),
            ("  custom-build-release-extras:", "  # Determines if we should publish"),
        ):
            dependent_job = workflow[
                workflow.index(job_start) : workflow.index(job_end)
            ]
            self.assertIn("- custom-release-checks", dependent_job)
        host = workflow[
            workflow.index("  host:") : workflow.index("  custom-publish-crates:")
        ]
        self.assertIn("- custom-release-checks", host)
        self.assertIn(
            "(needs.custom-release-checks.result == 'skipped' || "
            "needs.custom-release-checks.result == 'success')",
            host,
        )
        local_build = workflow[
            workflow.index("  build-local-artifacts:") : workflow.index(
                "  custom-release-checks:"
            )
        ]
        self.assertEqual(
            local_build.count('name: "Configure the portable release target"'),
            1,
        )
        self.assertLess(
            local_build.index('name: "Configure the portable release target"'),
            local_build.index("name: Install dist"),
        )
        for cpu in ("x86-64", "penryn", "apple-m1"):
            self.assertIn(f"target-cpu={cpu}", local_build)
        self.assertNotIn("custom-publish-pypi", workflow)
        self.assertLess(workflow.index("custom-publish-crates:"), workflow.index("announce:"))
        self.assertIn(
            "actions/attest@1e69f48acb82d1966a394da916b4c1698aa569d6",
            workflow,
        )
        self.assertNotIn("packaging/stage_binary.py", workflow)

        # All third-party actions in the generated and custom release workflows
        # are immutable commit references. Local reusable workflows are exempt.
        release_workflows = [
            ROOT / ".github/workflows/release.yml",
            ROOT / ".github/workflows/release-checks.yml",
            ROOT / ".github/workflows/portability.yml",
            ROOT / ".github/workflows/build-release-extras.yml",
            ROOT / ".github/workflows/publish-crates.yml",
            ROOT / ".github/workflows/publish-python.yml",
            ROOT / ".github/workflows/docs.yml",
        ]
        action_reference = re.compile(
            r"^\s*(?:-\s*)?uses:\s+[^./\s][^@\s]*@([0-9a-f]{40})(?:\s+#.*)?$"
        )
        for path in release_workflows:
            for line in path.read_text(encoding="utf-8").splitlines():
                if "uses:" in line and "./.github/" not in line:
                    self.assertRegex(
                        line, action_reference, f"unpinned action in {path}: {line}"
                    )

        crates = (ROOT / ".github/workflows/publish-crates.yml").read_text(encoding="utf-8")
        self.assertIn(
            "rust-lang/crates-io-auth-action@c6f97d42243bad5fab37ca0427f495c86d5b1a18",
            crates,
        )
        self.assertIn("environment: crates-io", crates)
        self.assertIn("cargo package --locked", crates)
        self.assertIn("Verify the complete immutable release set", crates)
        self.assertIn("packaging/verify_complete_release_set.py", crates)
        self.assertLess(
            crates.index("Verify the complete immutable release set"),
            crates.index("Obtain a short-lived crates.io credential"),
        )
        self.assertIn(".version.checksum", crates)
        self.assertIn("wait_until_visible", crates)
        self.assertNotIn("secrets.CARGO_REGISTRY_TOKEN", crates)
        python_publish = (ROOT / ".github/workflows/publish-python.yml").read_text(
            encoding="utf-8"
        )
        pinned_python = (
            "actions/setup-python@"
            "ece7cb06caefa5fff74198d8649806c4678c61a1"
        )
        for workflow_text in (crates, python_publish):
            self.assertEqual(workflow_text.count(pinned_python), 1)
            setup = workflow_text.index(pinned_python)
            release_version = workflow_text.index("packaging/release_version.py")
            self.assertIn("python-version: '3.13'", workflow_text[setup:release_version])
            self.assertLess(setup, release_version)
        self.assertIn("workflow_dispatch:", python_publish)
        self.assertNotIn("workflow_call:", python_publish)
        self.assertIn(
            "pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33",
            python_publish,
        )
        self.assertIn("name: pypi", python_publish)
        self.assertIn("isImmutable", python_publish)
        self.assertIn("gh release verify-asset", python_publish)
        self.assertIn("pypi.org/pypi/gravlax-client", python_publish)
        self.assertIn("published.items() <= expected.items()", python_publish)
        self.assertIn("packages-dir: pypi-upload", python_publish)
        self.assertIn("shutil.copy2", python_publish)
        self.assertNotIn("skip-existing:", python_publish)
        self.assertNotIn("secrets.PYPI", python_publish)
        release_checks = (ROOT / ".github/workflows/release-checks.yml").read_text(
            encoding="utf-8"
        )
        self.assertIn("Verify the annotated release tag", release_checks)
        self.assertIn('git cat-file -t "refs/tags/${RELEASE_TAG}"', release_checks)
        self.assertIn('refs/tags/${RELEASE_TAG}^{commit}', release_checks)
        self.assertIn('= "${GITHUB_SHA}"', release_checks)
        self.assertIn(
            "pip install --disable-pip-version-check -e './python[test]'",
            release_checks,
        )
        extras = (ROOT / ".github/workflows/build-release-extras.yml").read_text(
            encoding="utf-8"
        )
        for rust_workflow in (release_checks, crates, extras):
            self.assertIn("rustflags: ''", rust_workflow)
        self.assertIn(
            "anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610",
            extras,
        )
        self.assertIn("packaging/stage_source.py", extras)
        self.assertIn("readelf --program-headers", extras)
        self.assertIn(
            "actions/attest@1e69f48acb82d1966a394da916b4c1698aa569d6",
            extras,
        )
        self.assertIn("name: artifacts-build-release-extras", extras)

        maintenance = (ROOT / "packaging/README.md").read_text(encoding="utf-8")
        self.assertIn("top-level workflow `publish-python.yml`", maintenance)
        self.assertIn("workflow\n`release.yml`", maintenance)
        self.assertNotIn("workflow `publish-crates.yml`", maintenance)

    def test_pre_release_portability_links_and_smoke_tests_native_targets(self):
        portability = (ROOT / ".github/workflows/portability.yml").read_text(
            encoding="utf-8"
        )
        self.assertRegex(portability, r"(?m)^  pull_request:\s*$")
        self.assertRegex(portability, r"(?m)^  push:\s*$")
        self.assertIn("branches: [main]", portability)
        self.assertIn("workflow_dispatch:", portability)
        self.assertNotIn("tags:", portability)
        self.assertIn("windows-2022", portability)
        self.assertIn("ubuntu-22.04", portability)
        release_flags = {
            "x86_64-pc-windows-msvc": (
                "-Ctarget-cpu=x86-64 -Ctarget-feature=+crt-static"
            ),
            "x86_64-unknown-linux-musl": (
                "-Ctarget-cpu=x86-64 -Ctarget-feature=+crt-static "
                "-Clink-self-contained=yes"
            ),
        }
        for target, rustflags in release_flags.items():
            self.assertIn(target, portability)
            self.assertIn(f"target/{target}/dist/aie", portability)
            self.assertIn(f"rustflags: '{rustflags}'", portability)
        self.assertIn("toolchain: 1.98.0", portability)
        self.assertIn("target: ${{ matrix.target }}", portability)
        self.assertIn("rustflags: ''", portability)
        self.assertIn("RUSTFLAGS: ${{ matrix.rustflags }}", portability)
        self.assertIn(
            "cargo build --locked --profile dist --package gravlax --bin aie",
            portability,
        )
        self.assertIn("--target ${{ matrix.target }}", portability)
        self.assertGreaterEqual(portability.count('"${binary}" --version'), 2)
        self.assertEqual(portability.count('"${binary}" completions bash'), 2)
        self.assertIn("readelf --program-headers", portability)
        self.assertIn("Requesting program interpreter", portability)

    def test_release_cpu_policy_matches_cargo_dist_setup(self):
        expected = {
            "x86_64-unknown-linux-gnu": "x86-64",
            "x86_64-unknown-linux-musl": "x86-64",
            "x86_64-pc-windows-msvc": "x86-64",
            "x86_64-apple-darwin": "penryn",
            "aarch64-apple-darwin": "apple-m1",
        }
        cargo_config = tomllib.loads(
            (ROOT / ".cargo/config.toml").read_text(encoding="utf-8")
        )
        self.assertEqual(set(cargo_config["target"]), set(expected))
        for target, cpu in expected.items():
            self.assertEqual(
                cargo_config["target"][target]["rustflags"],
                ["-C", f"target-cpu={cpu}"],
            )

        setup = (
            ROOT / ".github/workflows/cargo-dist/release-build-setup.yml"
        ).read_text(encoding="utf-8")
        self.assertIn("unsupported or combined release target", setup)
        setup_arms = {
            (
                "x86_64-unknown-linux-gnu|x86_64-unknown-linux-musl|"
                "x86_64-pc-windows-msvc"
            ): "x86-64",
            "x86_64-apple-darwin": "penryn",
            "aarch64-apple-darwin": "apple-m1",
        }
        for arm, cpu in setup_arms.items():
            self.assertRegex(
                setup,
                rf"(?m)^\s*{re.escape(arm)}\)\s*$\n"
                rf"^\s*release_rustflags='-Ctarget-cpu={re.escape(cpu)}'\s*$",
            )
        self.assertIn("MACOSX_DEPLOYMENT_TARGET=10.12", setup)
        self.assertIn("MACOSX_DEPLOYMENT_TARGET=11.0", setup)

    def test_public_crates_ship_local_readmes_and_license_text(self):
        packages = (
            "gravlax-evidence-io",
            "gravlax-output",
            "gravlax-anno",
            "gravlax-ingest",
            "gravlax",
        )
        environment = {
            **os.environ,
            "RUSTUP_TOOLCHAIN": "1.98.0-x86_64-unknown-linux-gnu",
        }
        for package in packages:
            completed = subprocess.run(
                [
                    "cargo",
                    "package",
                    "--locked",
                    "--allow-dirty",
                    "--list",
                    "--package",
                    package,
                ],
                cwd=ROOT,
                check=True,
                capture_output=True,
                text=True,
                env=environment,
            )
            contents = set(completed.stdout.splitlines())
            self.assertIn("LICENSE", contents, package)
            self.assertIn("README.md", contents, package)

        root_license = (ROOT / "LICENSE").read_bytes()
        for relative in (
            "crates/evidence-io",
            "crates/gravlax-output",
            "crates/anno",
            "crates/ingest",
            "crates/aie",
        ):
            self.assertEqual((ROOT / relative / "LICENSE").read_bytes(), root_license)

    def test_binary_archives_are_deterministic_and_complete(self):
        with tempfile.TemporaryDirectory() as temporary:
            work = Path(temporary)
            binary = work / "aie"
            binary.write_text(
                "#!/bin/sh\n"
                "test \"$1\" = completions || exit 2\n"
                "printf '# completion for %s\\n' \"$2\"\n",
                encoding="utf-8",
            )
            binary.chmod(0o755)
            environment = {**os.environ, "SOURCE_DATE_EPOCH": "1788323967"}
            outputs = []
            for name in ("one", "two"):
                output = work / name
                subprocess.run(
                    [
                        PYTHON,
                        str(ROOT / "packaging/stage_binary.py"),
                        "--binary",
                        str(binary),
                        "--target",
                        "x86_64-unknown-linux-gnu",
                        "--version",
                        "0.1.0",
                        "--format",
                        "tar.gz",
                        "--output-dir",
                        str(output),
                        "--repository",
                        str(ROOT),
                    ],
                    check=True,
                    env=environment,
                    capture_output=True,
                )
                outputs.append(output / "gravlax-0.1.0-x86_64-unknown-linux-gnu.tar.gz")
            self.assertEqual(outputs[0].read_bytes(), outputs[1].read_bytes())
            with tarfile.open(outputs[0], "r:gz") as archive:
                names = set(archive.getnames())
                prefix = "gravlax-0.1.0-x86_64-unknown-linux-gnu"
                self.assertTrue(
                    {
                        f"{prefix}/aie",
                        f"{prefix}/LICENSE",
                        f"{prefix}/README.md",
                        f"{prefix}/completions/aie.bash",
                        f"{prefix}/completions/aie.zsh",
                        f"{prefix}/completions/aie.fish",
                    }.issubset(names)
                )
                self.assertTrue(archive.getmember(f"{prefix}/aie").mode & 0o111)

            windows_output = work / "windows"
            windows_binary = work / "aie.exe"
            windows_binary.write_bytes(binary.read_bytes())
            windows_binary.chmod(0o755)
            subprocess.run(
                [
                    PYTHON,
                    str(ROOT / "packaging/stage_binary.py"),
                    "--binary",
                    str(windows_binary),
                    "--target",
                    "x86_64-pc-windows-msvc",
                    "--version",
                    "0.1.0",
                    "--format",
                    "zip",
                    "--output-dir",
                    str(windows_output),
                    "--repository",
                    str(ROOT),
                ],
                check=True,
                env=environment,
                capture_output=True,
            )
            with zipfile.ZipFile(windows_output / "gravlax-0.1.0-x86_64-pc-windows-msvc.zip") as archive:
                self.assertIn(
                    "gravlax-0.1.0-x86_64-pc-windows-msvc/completions/aie.fish",
                    archive.namelist(),
                )

    def test_bioconda_renderer_binds_real_release_bytes(self):
        with tempfile.TemporaryDirectory() as temporary:
            work = Path(temporary)
            archive = work / "gravlax-0.1.0-source.tar.gz"
            archive.write_bytes(b"immutable release source bytes")
            output = work / "recipe/meta.yaml"
            subprocess.run(
                [
                    PYTHON,
                    str(ROOT / "packaging/bioconda/render_recipe.py"),
                    "--version",
                    "0.1.0",
                    "--source-archive",
                    str(archive),
                    "--output",
                    str(output),
                ],
                check=True,
                capture_output=True,
            )
            rendered = output.read_text(encoding="utf-8")
            expected = hashlib.sha256(archive.read_bytes()).hexdigest()
            self.assertIn(expected, rendered)
            self.assertIn("releases/download/v{{ version }}", rendered)
            self.assertIn("cargo install --locked --offline", rendered)
            self.assertNotIn("@VERSION@", rendered)
            self.assertNotIn("@SOURCE_SHA256@", rendered)
            second = subprocess.run(
                [
                    PYTHON,
                    str(ROOT / "packaging/bioconda/render_recipe.py"),
                    "--version",
                    "0.1.0",
                    "--source-archive",
                    str(archive),
                    "--output",
                    str(output),
                ],
                capture_output=True,
            )
            self.assertNotEqual(second.returncode, 0)
            self.assertIn("refusing to overwrite", second.stderr.decode())

    def test_extra_checksum_manifest_is_complete_and_non_overwriting(self):
        version = "0.1.0"
        names = {
            f"gravlax-{version}-source.tar.gz",
            f"gravlax-{version}.spdx.json",
            f"gravlax_client-{version}-py3-none-any.whl",
            f"gravlax_client-{version}.tar.gz",
        }
        with tempfile.TemporaryDirectory() as temporary:
            directory = Path(temporary)
            for name in names:
                (directory / name).write_bytes(name.encode("ascii"))
            command = [
                PYTHON,
                str(ROOT / "packaging/verify_release_set.py"),
                str(directory),
                "--version",
                version,
            ]
            subprocess.run(command, check=True, capture_output=True)
            lines = (directory / "SHA256SUMS").read_text(encoding="ascii").splitlines()
            self.assertEqual(len(lines), len(names))
            self.assertEqual([line.split("  ", 1)[1] for line in lines], sorted(names))
            second = subprocess.run(command, capture_output=True)
            self.assertNotEqual(second.returncode, 0)

    def test_extra_asset_manifest_preserves_the_bioconda_source_contract(self):
        version = "0.1.0"
        names = {
            f"gravlax-{version}-source.tar.gz",
            f"gravlax-{version}.spdx.json",
            f"gravlax_client-{version}-py3-none-any.whl",
            f"gravlax_client-{version}.tar.gz",
        }
        with tempfile.TemporaryDirectory() as temporary:
            directory = Path(temporary)
            for name in names:
                (directory / name).write_bytes(name.encode("ascii"))
            subprocess.run(
                [
                    PYTHON,
                    str(ROOT / "packaging/verify_release_set.py"),
                    str(directory),
                    "--version",
                    version,
                ],
                check=True,
                capture_output=True,
            )
            manifest = (directory / "SHA256SUMS").read_text(encoding="ascii")
            self.assertIn(f"gravlax-{version}-source.tar.gz", manifest)

    def test_complete_release_set_is_exact_and_content_verified(self):
        version = "0.1.1"
        targets = {
            "aarch64-apple-darwin": ".tar.gz",
            "x86_64-apple-darwin": ".tar.gz",
            "x86_64-pc-windows-msvc": ".zip",
            "x86_64-unknown-linux-gnu": ".tar.gz",
            "x86_64-unknown-linux-musl": ".tar.gz",
        }
        with tempfile.TemporaryDirectory() as temporary:
            directory = Path(temporary)
            archives = {
                f"gravlax-{target}{suffix}" for target, suffix in targets.items()
            }
            for name in archives:
                (directory / name).write_bytes(name.encode("ascii"))
                digest = hashlib.sha256((directory / name).read_bytes()).hexdigest()
                (directory / f"{name}.sha256").write_text(
                    f"{digest} *{name}\n", encoding="ascii"
                )
            (directory / "sha256.sum").write_text(
                "".join(
                    f"{hashlib.sha256((directory / name).read_bytes()).hexdigest()} *{name}\n"
                    for name in sorted(archives)
                ),
                encoding="ascii",
            )
            extras = {
                f"gravlax-{version}-source.tar.gz",
                f"gravlax-{version}.spdx.json",
                f"gravlax_client-{version}-py3-none-any.whl",
                f"gravlax_client-{version}.tar.gz",
            }
            for name in extras:
                (directory / name).write_bytes(name.encode("ascii"))
            (directory / "SHA256SUMS").write_text(
                "".join(
                    f"{hashlib.sha256((directory / name).read_bytes()).hexdigest()}  {name}\n"
                    for name in sorted(extras)
                ),
                encoding="ascii",
            )
            for name in ("gravlax-installer.ps1", "gravlax-installer.sh"):
                (directory / name).write_bytes(name.encode("ascii"))
            (directory / "dist-manifest.json").write_text(
                json.dumps(
                    {
                        "announcement_tag": f"v{version}",
                        "releases": [
                            {"app_name": "gravlax", "app_version": version}
                        ],
                    }
                ),
                encoding="utf-8",
            )
            command = [
                PYTHON,
                str(ROOT / "packaging/verify_complete_release_set.py"),
                str(directory),
                "--version",
                version,
            ]
            subprocess.run(command, check=True, capture_output=True)

            missing = directory / "gravlax-installer.sh"
            missing.unlink()
            rejected = subprocess.run(command, capture_output=True)
            self.assertNotEqual(rejected.returncode, 0)

    def test_vendored_source_preserves_the_release_cpu_policy(self):
        version = tomllib.loads((ROOT / "Cargo.toml").read_text(encoding="utf-8"))[
            "workspace"
        ]["package"]["version"]
        with tempfile.TemporaryDirectory() as temporary:
            output = Path(temporary)
            subprocess.run(
                [
                    PYTHON,
                    str(ROOT / "packaging/stage_source.py"),
                    "--repository",
                    str(ROOT),
                    "--revision",
                    "HEAD",
                    "--version",
                    version,
                    "--output-dir",
                    str(output),
                ],
                check=True,
                capture_output=True,
                env={**os.environ, "SOURCE_DATE_EPOCH": "1788408000"},
            )
            archive_path = output / f"gravlax-{version}-source.tar.gz"
            with tarfile.open(archive_path, "r:gz") as archive:
                config_member = archive.getmember(
                    f"gravlax-{version}/.cargo/config.toml"
                )
                extracted = archive.extractfile(config_member)
                self.assertIsNotNone(extracted)
                config = extracted.read().decode("utf-8")
                for cpu in ("x86-64", "penryn", "apple-m1"):
                    self.assertIn(f"target-cpu={cpu}", config)
                self.assertIn('[source.crates-io]', config)
                self.assertIn('directory = "vendor"', config)
                self.assertIn("[net]\noffline = true", config)
                self.assertTrue(
                    any(
                        name.startswith(f"gravlax-{version}/vendor/")
                        for name in archive.getnames()
                    )
                )


if __name__ == "__main__":
    unittest.main()
