from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import Mock, patch

from gravlax import ProtocolError, read_mex


def metadata(**overrides):
    data = {
        "format": "matrix_market_coordinate",
        "matrix": "matrix.mtx",
        "features": "features.tsv",
        "barcodes": "barcodes.tsv",
        "feature_count": 2,
        "barcode_count": 2,
        "nonzero_count": 3,
        "index_base": 1,
        "value_type": "integer",
    }
    data.update(overrides)
    return {
        "$schema": "gravlax.result-envelope.v1",
        "result_schema": "gravlax.replay.gene-matrix.v1",
        "producer": {"name": "aie", "version": "0.1.0"},
        "provenance": {"archives": ["sample.aie"], "parameters": {}},
        "warnings": [],
        "data": data,
    }


class MexTests(unittest.TestCase):
    def make_mex(self, root: Path, **overrides):
        (root / "matrix.mtx").write_text(
            "%%MatrixMarket matrix coordinate integer general\n"
            "% generated by Gravlax\n"
            "2 2 3\n"
            "1 1 2\n"
            "1 2 3\n"
            "2 2 4\n",
            encoding="utf-8",
        )
        (root / "features.tsv").write_text(
            "ENSG1\tAlpha\\tOne\tGene Expression\n"
            "ENSG2\tBeta\tGene Expression\n",
            encoding="utf-8",
        )
        (root / "barcodes.tsv").write_text("CELL-1\nCELL-2\n", encoding="utf-8")
        (root / "metadata.json").write_text(
            json.dumps(metadata(**overrides)), encoding="utf-8"
        )

    def test_reads_labels_and_manifest_without_optional_dependencies(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self.make_mex(root)

            dataset = read_mex(root)

            self.assertEqual(dataset.features()[0].name, "Alpha\tOne")
            self.assertEqual(dataset.barcodes(), ("CELL-1", "CELL-2"))
            self.assertEqual(dataset.envelope.result_schema, "gravlax.replay.gene-matrix.v1")

    def test_requires_completion_marker(self):
        with tempfile.TemporaryDirectory() as temporary:
            with self.assertRaisesRegex(ProtocolError, "completion marker"):
                read_mex(temporary)

    def test_rejects_manifest_path_escape(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self.make_mex(root, matrix="../outside.mtx")
            with self.assertRaisesRegex(ProtocolError, "directly inside"):
                read_mex(root)

    def test_rejects_dimension_mismatch(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self.make_mex(root, nonzero_count=4)
            with self.assertRaisesRegex(ProtocolError, "dimensions"):
                read_mex(root)

    def test_rejects_truncated_coordinates(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self.make_mex(root)
            (root / "matrix.mtx").write_text(
                "%%MatrixMarket matrix coordinate integer general\n"
                "2 2 3\n"
                "1 1 2\n"
                "1 2 3\n",
                encoding="utf-8",
            )
            with self.assertRaisesRegex(ProtocolError, "truncated"):
                read_mex(root)

    def test_rejects_out_of_bounds_coordinate(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self.make_mex(root)
            (root / "matrix.mtx").write_text(
                "%%MatrixMarket matrix coordinate integer general\n"
                "2 2 3\n"
                "1 1 2\n"
                "1 2 3\n"
                "3 2 4\n",
                encoding="utf-8",
            )
            with self.assertRaisesRegex(ProtocolError, "out of bounds"):
                read_mex(root)

    def test_rejects_duplicate_coordinate(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self.make_mex(root)
            (root / "matrix.mtx").write_text(
                "%%MatrixMarket matrix coordinate integer general\n"
                "2 2 3\n"
                "1 1 2\n"
                "1 1 3\n"
                "2 2 4\n",
                encoding="utf-8",
            )
            with self.assertRaisesRegex(ProtocolError, "duplicates"):
                read_mex(root)

    def test_rejects_duplicate_feature_ids(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self.make_mex(root)
            (root / "features.tsv").write_text(
                "ENSG1\tAlpha\tGene Expression\n"
                "ENSG1\tBeta\tGene Expression\n",
                encoding="utf-8",
            )
            with self.assertRaisesRegex(ProtocolError, "duplicate feature id"):
                read_mex(root)

    def test_rejects_duplicate_barcodes(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self.make_mex(root)
            (root / "barcodes.tsv").write_text("CELL-1\nCELL-1\n", encoding="utf-8")
            with self.assertRaisesRegex(ProtocolError, "duplicate barcode"):
                read_mex(root)

    def test_rejects_matrix_replaced_after_dataset_validation(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self.make_mex(root)
            dataset = read_mex(root)
            replacement = root / "replacement.mtx"
            replacement.write_text(
                "%%MatrixMarket matrix coordinate integer general\n"
                "2 2 3\n"
                "1 1 20\n"
                "1 2 30\n"
                "2 2 40\n",
                encoding="utf-8",
            )
            replacement.replace(root / "matrix.mtx")

            mmread = Mock(side_effect=AssertionError("mutated matrix must not be decoded"))
            with patch(
                "gravlax.mex._optional",
                return_value=SimpleNamespace(mmread=mmread),
            ):
                with self.assertRaisesRegex(ProtocolError, "changed"):
                    dataset.to_scipy()
            mmread.assert_not_called()

    def test_rejects_labels_replaced_after_dataset_validation(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self.make_mex(root)
            dataset = read_mex(root)
            replacement = root / "replacement.tsv"
            replacement.write_text(
                "ENSG1\tChanged\tGene Expression\n"
                "ENSG2\tBeta\tGene Expression\n",
                encoding="utf-8",
            )
            replacement.replace(root / "features.tsv")
            with self.assertRaisesRegex(ProtocolError, "changed"):
                dataset.features()

        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self.make_mex(root)
            dataset = read_mex(root)
            replacement = root / "replacement.tsv"
            replacement.write_text("OTHER-1\nOTHER-2\n", encoding="utf-8")
            replacement.replace(root / "barcodes.tsv")
            with self.assertRaisesRegex(ProtocolError, "changed"):
                dataset.barcodes()


if __name__ == "__main__":
    unittest.main()
